build-job:
  stage: build
  image: python # other Debian-based images may work, the CLI requires glibc.
  variables:
    TIDELIFT_API_KEY: $TIDELIFT_API_KEY_PROTECTED_VARIABLE # this should be kept in a GitLab Protected Variable https://docs.gitlab.com/ee/ci/variables/#create-a-custom-variable-in-the-ui
  script:
    - echo "Downloading Tidelift CLI"
    - curl https://download.tidelift.com/cli/tidelift -o tidelift
    - echo "Setting permissions"
    - chmod +x tidelift
    - echo "Runnning alignment and saving to Tidelift"
    - ./tidelift alignment save --wait
